### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by dejury**
Make the package compatibly with Laravel 8

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Just out of curiosity, are you using this package?

**Comment by dejury** [comment]
Yes, I just started using it. I am working on a project where the lights need to go on (and off) when a fire alarm is there. I used that functionality before using IFTTT, but this way I can have more control over it.

**Comment by Cannonb4ll** [comment]
Interesting, I might do some more work on this package soon. Have not done anything with it for a long while now.

**Comment by dejury** [comment]
Well it was mentioned on several articles on the internet, so thats why I started using it. Well and I'm using ploi for a while now, so when I saw you are related with ploi, that was a plus ;)

**Pull request merged**
